### ISSUE TITLE
Typos on retirement page 

### ISSUE THREAD

**Issue by roertbb** [tomaszgil/osobista-emerytura#30]
I've noticed that on https://osobistaemerytura.pl/emerytura there are small typos that could be fixed.
For example:
- title `Fiananse bardzo osobiste` should be `Finanse bardzo osobiste`
- `Dla punku pierwszego...` should be rather `Dla punktu pierwszego...`
- and some more 😉

**Comment by tomaszgil** [comment]
@roertbb awesome, thanks for contributing! 🙏
